name: Nightly KPI refresh
on:
  schedule: # run every day
    - cron: "5 6 * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      JIRA_BASE: ${{ secrets.JIRA_BASE }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install -r requirements.txt

      - name: Re-ingest & rebuild
        run: |
          python ingest/github_pull.py --days 90 --token $GH_PAT
          python ingest/jira_pull.py    --days 30

          # Check if GitHub events file has data before proceeding
          if [[ $(du -k "data/raw/github_events.parquet" | cut -f1) -gt 1 ]]; then
            python models/build_kpis.py
          else
            echo "Skipping KPI build: github_events.parquet is empty"
          fi

      - name: Commit updated DB
        run: |
          git config user.name  "kpi-bot"
          git config user.email "bot@example.com"
          git add data/observatory.duckdb
          git commit -m "chore: nightly KPI refresh" || echo "no diff"
          git push
